# This workflow will build a Java project with Gradle
name: github-actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
        run: |
          # Create directory for certs if not exists
          mkdir -p certs

          # Save private key to certs/private.pem
          echo "$PRIVATE_KEY" > certs/private.pem

          # Save public key to certs/public.pem
          echo "$PUBLIC_KEY" > certs/public.pem
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco